### ISSUE TITLE
springBoot h2 연결

### ISSUE THREAD

**Issue by ohyeryung** [ohyeryung/mini_project#1]
application.properties

```
# SQL 문장을 로그에 출력할지 여부 설정
spring.jpa.show-sql=true

# 예쁘게 포맷된 SQL 문장을 출력할지 여부 설정
spring.jpa.properties.hibernate.format_sql=true

 # Hibernate의 H2Dialect를 사용하여 H2와 연동
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true # H2 Console 사용 여부 (console 사용 시 localhost로 연결해 DB UI 를 볼 수 있음)
spring.h2.console.path=/h2-console # H2 Console의 경로 설정

spring.datasource.driver-class-name=org.h2.Driver # H2 데이터베이스 드라이버 클래스 설정

spring.datasource.url=jdbc:h2:~/test # H2 데이터베이스 접속 URL 설정
spring.datasource.username=sa # H2 데이터베이스 접속 시 사용할 username 설정
spring.datasource.password= # H2 데이터베이스 접속 시 사용할 password 설정

```

application.yml
```
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect 
  h2:
    console:
      enabled: true  
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver  
    url: jdbc:h2:~/test 
    username: sa
    password:
```
